# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0024f8f0762e90ecc00a8d91d17d1f8a85ba717763f752787823f81ae0d85f045e3ac4f345df165d8be73e20710aed939171eec0e0d8ba95ffa1f3ff69c74e9

test:
  secret_key_base: 32b632501839099c0a23a7126773964f3a3804392c4815b3889ffd4b73a956c4305e476de30a7032eb35488dd70b15e1ce13d2ecd56ae80d8035ab904b4d13a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
